name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 11 Pro,OS=latest"]
    steps:
      - uses: actions/checkout@v1
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -workspace "Depromeet8th4.xcworkspace" -scheme "Depromeet8th4" -destination "${{ matrix.destination }}"
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: --strict
